<a href="https://colab.research.google.com/github/minkyeongk/Deep_Learning_Specialization/blob/main/week_2_python_numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a = np.random.randn(5)
# 임의로 5개의 gaussian 변수를 생성

In [4]:
print(a)

[ 0.8832434   0.43685144 -0.73716314 -1.91963749 -0.64732679]


In [5]:
print(a.shape)
# 대괄호 하나 rank 1 array > neither row vector nor column vector

(5,)


In [6]:
print(a.T)

[ 0.8832434   0.43685144 -0.73716314 -1.91963749 -0.64732679]


In [9]:
print(np.dot(a, a.T))
# transpose: 전치
# inner product (내적) 결과 > matrix가 아닌 숫자 

5.618407667885578


In [10]:
 a = np.random.randn(5, 1) # a가 5*1 세로 벡터가 되도록 
 print(a)
 # 대괄호 두개 > matrix 

[[ 0.1361066 ]
 [-0.49890689]
 [-0.87696188]
 [ 0.83152507]
 [ 0.5207804 ]]


In [11]:
print(a.T)  # 전치 행렬이 row vector의 형태를 보임 

[[ 0.1361066  -0.49890689 -0.87696188  0.83152507  0.5207804 ]]


In [12]:
print(np.dot(a, a.T))

[[ 0.01852501 -0.06790452 -0.1193603   0.11317605  0.07088165]
 [-0.06790452  0.24890808  0.43752232 -0.41485359 -0.25982093]
 [-0.1193603   0.43752232  0.76906213 -0.72921579 -0.45670456]
 [ 0.11317605 -0.41485359 -0.72921579  0.69143394  0.43304196]
 [ 0.07088165 -0.25982093 -0.45670456  0.43304196  0.27121222]]
