<a href="https://colab.research.google.com/github/minkyeongk/Deep_Learning_Specialization/blob/main/week_2_Broadcasting_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percent = 100 * A/cal.reshape(1,4)
print(percent)
# A를 1*4 퍼센트 행렬로 나눔 

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
